version: "2"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html/
    volumes:
      - ./docker/logs/nginx:/var/log/nginx
      - ./src:/var/www/html
      - ./docker/images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
      - "444:443"

  fpm:
    build: ./docker/images/php
    container_name: fpm
    volumes:
      - ./src:/var/www/html/
    working_dir: /var/www/html/
  mysql:
    image: mysql:8
    container_name: mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--max_allowed_packet=256M"]
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user_test
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./docker/data/mysql-data:/var/lib/mysql/
      - ./docker/logs/mysql:/var/log/mysql
    ports:
      - "3307:3306"