<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKdk7xsZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKdk7xsZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKdk7xsZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKdk7xsZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKdk7xsZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kdk7xsZ',
    'container.build_id' => '55da291a',
    'container.build_time' => 1638603614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKdk7xsZ');
